services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: fiestou_app
        container_name: fiestou_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./src/vendor:/var/www/html/vendor
            - ./public:/var/www/html/public
            - ./storage:/var/www/html/storage
        expose:
            - "9000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:1U3JhzlQTO4C5FlM0Q6XO0eQKk5hfQyKk34Ldfhfxc0=
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: fiestou_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
            - ./public:/var/www/html/public
            - ./storage:/var/www/html/storage
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=fiesto18_database
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql-data:
