name: 🛠️ Backend
description: Template simplificado para tarefas de backend (Feature ou Chore)
title: "[backend][feat|chore] Descreva a tarefa"
labels: ["backend"]
body:
  - type: dropdown
    id: tipo
    attributes:
      label: Tipo da tarefa
      options:
        - feat (nova funcionalidade)
        - chore (manutenção/infra)
    validations:
      required: true

  - type: textarea
    id: descricao
    attributes:
      label: 📄 Descrição
      description: O que precisa ser feito? Contexto rápido para entender a necessidade.
      placeholder: >
        Exemplo:
        Criar endpoint POST /clientes para permitir cadastro de novos clientes.
    validations:
      required: true

  - type: textarea
    id: objetivo
    attributes:
      label: 🎯 Objetivo
      description: Qual o resultado esperado após concluir a tarefa?
      placeholder: >
        Exemplo:
        Possibilitar que o frontend envie dados de novos clientes para o sistema.
    validations:
      required: true

  - type: textarea
    id: testes
    attributes:
      label: ✅ Critérios de aceitação e testes
      description: DOD + plano de testes (unit/integration/e2e), mocks e cenários.
      placeholder: >
        Critérios:
        - [ ] POST /v1/orders retorna 400 quando payment_method inválido
        - [ ] Log de falha gravado com correlationId
        - [ ] Métrica de erro incrementa em caso 400
        Testes:
        - Unit: validar PaymentMethodValidator
        - Integração: contrato com PaymentGateway mockado
        - E2E: fluxo completo com DB real (staging)

  - type: textarea
    id: referencias
    attributes:
      label: 🔗 Referências (opcional)
      description: Links úteis (issues relacionadas, documentação, API schema, etc.).
      placeholder: >
        https://swagger.io/... | Issue #123


  - type: textarea
    id: regras
    attributes:
      label: 📐 Regras de negócio
      description: Regras claras, edge cases e fluxos alternativos.
      placeholder: >
        - payment_method ∈ {credit_card, pix, boleto}
        - Se status=cancelled, não permitir transição para paid...
